schema = """{'schema': [{'cid': 0, 'name': 'year', 'type': 'INTEGER'},
  {'cid': 1, 'name': 'month_num', 'type': 'INTEGER'},
  {'cid': 2, 'name': 'town', 'type': 'VARCHAR'},
  {'cid': 3, 'name': 'flat_type', 'type': 'VARCHAR'},
  {'cid': 4, 'name': 'block', 'type': 'VARCHAR'},
  {'cid': 5, 'name': 'street_name', 'type': 'VARCHAR'},
  {'cid': 6, 'name': 'storey_range', 'type': 'VARCHAR'},
  {'cid': 7, 'name': 'floor_area_sqm', 'type': 'DOUBLE'},
  {'cid': 8, 'name': 'flat_model', 'type': 'VARCHAR'},
  {'cid': 9, 'name': 'lease_commence_date', 'type': 'INTEGER'},
  {'cid': 10, 'name': 'remaining_lease', 'type': 'VARCHAR'},
  {'cid': 11, 'name': 'resale_price', 'type': 'DOUBLE'}],
 'categories': {'flat_type': ['1 ROOM',
   '2 ROOM',
   '3 ROOM',
   '4 ROOM',
   '5 ROOM',
   'EXECUTIVE',
   'MULTI-GENERATION'],
  'town': ['ANG MO KIO',
   'BEDOK',
   'BISHAN',
   'BUKIT BATOK',
   'BUKIT MERAH',
   'BUKIT PANJANG',
   'BUKIT TIMAH',
   'CENTRAL AREA',
   'CHOA CHU KANG',
   'CLEMENTI',
   'GEYLANG',
   'HOUGANG',
   'JURONG EAST',
   'JURONG WEST',
   'KALLANG/WHAMPOA',
   'MARINE PARADE',
   'PASIR RIS',
   'PUNGGOL',
   'QUEENSTOWN',
   'SEMBAWANG',
   'SENGKANG',
   'SERANGOON',
   'TAMPINES',
   'TOA PAYOH',
   'WOODLANDS',
   'YISHUN'],
  'flat_model': ['2-room',
   '3Gen',
   'Adjoined flat',
   'Apartment',
   'DBSS',
   'Improved',
   'Improved-Maisonette',
   'Maisonette',
   'Model A',
   'Model A-Maisonette',
   'Model A2',
   'Multi Generation',
   'New Generation',
   'Premium Apartment',
   'Premium Apartment Loft',
   'Premium Maisonette',
   'Simplified',
   'Standard',
   'Terrace',
   'Type S1',
   'Type S2'],
  'storey_range': ['01 TO 03',
   '04 TO 06',
   '07 TO 09',
   '10 TO 12',
   '13 TO 15',
   '16 TO 18',
   '19 TO 21',
   '22 TO 24',
   '25 TO 27',
   '28 TO 30',
   '31 TO 33',
   '34 TO 36',
   '37 TO 39',
   '40 TO 42',
   '43 TO 45',
   '46 TO 48',
   '49 TO 51']}}"""